export const bookInterests = [
  {value: "Fiction", label: "Fiction"},
  {value:"Non-Fiction", label: "Non-Fiction"},
  {value: "Fantasy", label: "Fantasy"},
  {value: "Science Fiction-fi", label: "Science Fiction"},
  {value: "Mystery", label:"Mystery"},
  {value: "Thriller", label:"Thriller"},
  {value: "Romance", label:"Romance"},
  {value: "Historical Fiction", label:"Historical Fiction"},
  {value: "Horror", label:"Horror"},
  {value: "Poetry", label:"Poetry"},
  {value: "Classic Literature", label:"Classic Literature"},
  {value: "Young Adult", label:"Young Adult"},
  {value: "Biography", label:"Biography"},
  { value: "Self-help", label: "Self-help" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Psychology", label: "Psychology" },
  { value: "Graphic Novels", label: "Graphic Novels" },
  { value: "Contemporary Fiction", label: "Contemporary Fiction" },
  { value: "Adventure", label: "Adventure" },
  { value: "Short Stories", label: "Short Stories" },
  { value: "Book-to-Movie Adaptations", label: "Book-to-Movie Adaptations" },
  { value: "Modern Authors", label: "Modern Authors" },
  { value: "Book Clubs", label: "Book Clubs" },
  { value: "Writing & Publishing", label: "Writing & Publishing" },    
]

export const cinemaInterests = [
  { value: "Action", label: "Action" },
  { value: "Drama", label: "Drama" },
  { value: "Comedy", label: "Comedy" },
  { value: "Romance", label: "Romance" },
  { value: "Thriller", label: "Thriller" },
  { value: "Horror", label: "Horror" },
  { value: "Science Fiction", label: "Science Fiction" },
  { value: "Fantasy", label: "Fantasy" },
  { value: "Documentary", label: "Documentary" },
  { value: "Animation", label: "Animation" },
  { value: "Musicals", label: "Musicals" },
  { value: "Crime", label: "Crime" },
  { value: "Mystery", label: "Mystery" },
  { value: "Adventure", label: "Adventure" },
  { value: "Historical", label: "Historical" },
  { value: "Indie Films", label: "Indie Films" },
  { value: "Superhero", label: "Superhero" },
  { value: "Classic Films", label: "Classic Films" },
  { value: "International Cinema", label: "International Cinema" },
  { value: "Cinematography", label: "Cinematography" },
  { value: "Film Direction", label: "Film Direction" },
  { value: "Screenwriting", label: "Screenwriting" },
  { value: "Actors & Performances", label: "Actors & Performances" },
  { value: "Film Analysis & Reviews", label: "Film Analysis & Reviews" },
  { value: "Book-to-Film Adaptations", label: "Book-to-Film Adaptations" }
]




